/* generated by pull.js */
const manifest = {
    "name": "移动端全屏",
    "description": "在手机上添加全屏按钮，自动缩放编辑器以适应屏幕。",
    "credits": [
        {
            "name": "wangwenhao20211",
            "link": "https://space.bilibili.com/1512219051"
        }
    ],
    "tags": [],
    "enabledByDefault": false,
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "dynamicDisable": false
};
export default manifest;