/* generated by pull.js */
const manifest = {
    "name": "Eruda 控制台",
    "description": "在无控制台浏览器轻松进行调试。",
    "credits": [
        {
            "name": "wangwenhao20211",
            "link": "https://space.bilibili.com/1512219051"
        }
    ],
    "tags": [
        "new"
    ],
    "enabledByDefault": false,
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "dynamicDisable": false
};
export default manifest;